import connectToDatabase from "@/lib/mongodb";
import { Event } from "@/database";
import { NextRequest, NextResponse } from "next/server";

// Slugs are generated by `slugify()` in the Event model: lowercase letters,
// numbers, and single hyphens, with no leading/trailing hyphen.
const SLUG_REGEX = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  try {
    const { slug } = await params;

    if (!slug || typeof slug !== "string" || !SLUG_REGEX.test(slug)) {
      return NextResponse.json(
        { message: "A valid event slug is required" },
        { status: 400 }
      );
    }

    await connectToDatabase();

    const event = await Event.findOne({ slug });

    if (!event) {
      return NextResponse.json(
        { message: `No event found with slug "${slug}"` },
        { status: 404 }
      );
    }

    return NextResponse.json(
      { message: "Event fetched successfully", event },
      { status: 200 }
    );
  } catch (e) {
    console.error(e);
    return NextResponse.json(
      {
        message: "Event fetching failed",
        error: e instanceof Error ? e.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
