export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit 2026",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "June 12, 2026",
    time: "09:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "GitHub Universe",
    slug: "github-universe",
    location: "San Francisco, CA",
    date: "October 28, 2026",
    time: "10:00 AM",
  },
  {
    image: "/images/event3.png",
    title: "JSConf EU",
    slug: "jsconf-eu",
    location: "Berlin, Germany",
    date: "June 6, 2026",
    time: "09:30 AM",
  },
  {
    image: "/images/event4.png",
    title: "AI Engineer Summit",
    slug: "ai-engineer-summit",
    location: "New York, NY",
    date: "February 20, 2026",
    time: "08:30 AM",
  },
  {
    image: "/images/event5.png",
    title: "Hack the North",
    slug: "hack-the-north",
    location: "Waterloo, Canada",
    date: "September 12, 2026",
    time: "12:00 PM",
  },
  {
    image: "/images/event6.png",
    title: "PyCon US",
    slug: "pycon-us",
    location: "Pittsburgh, PA",
    date: "May 14, 2026",
    time: "09:00 AM",
  },
];
